### ISSUE TITLE
chart not rendering after refresh

### ISSUE THREAD

**Issue by AuslinPJ** [AuslinPJ/mockstockaid#1]

**Comment by salatematha** [comment]
Hi Auslin,

Your chart is working now see screenshot. one character error. Typescript /
Javascript is case sensitive

In barchartcomponent html change hdata to hData and it works

<p-chart type="line" #Chart [data]="hdata"  ></p-chart>

[image: Inline image 1]

Thanks,
Dheepan.

**Comment by AuslinPJ** [comment]
thank you.
